version: "3.9"

services:
  app:
    build: .
    container_name: spring-app

    ports:
      - "8080:8080"

    environment:
      TZ: Asia/Ho_Chi_Minh
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Ho_Chi_Minh"
      THREADS_ACCESS_TOKEN: ${THREADS_ACCESS_TOKEN}

    tty: true
    stdin_open: true

    command: >
      sh -c "
      echo '🚀 Application will start at http://localhost:8080';
      mvn -q -T 1C -Dspring-boot.run.fork=false \
      -Dspring-boot.run.jvmArguments='-Duser.timezone=Asia/Ho_Chi_Minh' \
      spring-boot:run
      "

volumes:
  maven-cache: