version: "3.9"

services:
  app:
    image: maven:3.9.9-eclipse-temurin-17
    container_name: spring-dev
    working_dir: /workspace

    volumes:
      - .:/workspace
      - maven-cache:/root/.m2
      - ./data:/workspace/data

    ports:
      - "8080:8080"

    environment:
      THREADS_ACCESS_TOKEN: ${THREADS_ACCESS_TOKEN}

    tty: true
    stdin_open: true

    command: >
      sh -c "
      echo '🚀 Application will start at http://localhost:8080';
      mvn -q -T 1C -Dspring-boot.run.fork=false spring-boot:run
      "

volumes:
  maven-cache: