# Threads API Config
threads.access.token=${THREADS_ACCESS_TOKEN}

# Time run scan job (minutes)
scheduler.post.interval-minutes=1

#Paging in list post
posts.page-size=8

# Logging Config
logging.level.com.example.autopost=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n